### ISSUE TITLE
Failed to set the driver - Ubuntu 16.04 with Python bindings

### ISSUE THREAD

**Issue by rbedi** [h5s3/h5s3#11]
I installed `h5s3` using `python setup.py install` Ubuntu 16.04 with gcc version 7.1.0 and libhdf5-cpp-11 / libhdf5-dev 1.8.16. I'm using `h5py==2.8.0rc1`. 

I'm able to register the driver, but get the following error when I attempt to open a file like this:

```
f = h5py.File(
    matrices_file,
    'r+',
    driver='h5s3',
    aws_access_key=ACCESS_KEY,
    aws_secret_key=SECRET_KEY,
)
```
Error:
```
~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    309             name = filename_encode(name)
    310             with phil:
--> 311                 fapl = make_fapl(driver, libver, **kwds)
    312                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    313 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/h5py/_hl/files.py in make_fapl(driver, libver, **kwds)
    115         raise ValueError('Unknown driver type "%s"' % driver)
    116     else:
--> 117         set_fapl(plist, **kwds)
    118 
    119     return plist

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/h5s3-0.1.0-py3.6-linux-x86_64.egg/h5s3/__init__.py in set_fapl(plist, aws_access_key, aws_secret_key, aws_region, page_size, page_cache_size, host, use_tls)
     51         aws_region,
     52         host,
---> 53         use_tls,
     54     )
     55 

ValueError: failed to set the driver
```

**Comment by rbedi** [comment]
I obtain the following error when I run `python testcase.py`:

```
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140210935707456:
  #000: ../../../src/H5Pfapl.c line 674 in H5Pset_driver(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
Traceback (most recent call last):
  File "testcase.py", line 12, in <module>
    mode='r+',
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/h5py/_hl/files.py", line 311, in __init__
    fapl = make_fapl(driver, libver, **kwds)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/h5py/_hl/files.py", line 117, in make_fapl
    set_fapl(plist, **kwds)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/h5s3-0.1.0-py3.6-linux-x86_64.egg/h5s3/__init__.py", line 53, in set_fapl
    use_tls,
ValueError: failed to set the driver
```

**Comment by llllllllll** [comment]
There error you are seeing is coming from https://github.com/h5s3/h5s3/blob/master/bindings/python/h5s3/_h5s3.cc#L56. Right now we don't communicate any of the errors from the driver registration back to Python so this is just a catch-all. We should definitely look into how h5py surfaces hdf5 errors back to Python. For now, I think the best thing to do would be to set a breakpoint on line 48 and step through until this fails and see what the issue is.

This is not even making it to the file open, it is just failing setting the file access property list. Right now the only way this fails is if registration of the class hdf5 driver class fails, or `H5P_set_driver` fails. I haven't seen those fail, so one theory is that you compiled your h5s3 library against a different version of hdf5 than h5py was compiled against.

**Comment by rbedi** [comment]
Awesome, thank you; that's exactly what was happening. I re-compiled h5py against the same version of HDF5 that I compiled h5s3 against and made it past that! 

It's now failing at the actual file opening step (removed identifying information about buckets and endpoints). I verified that the aws_region is correct (us-west-2) and that this file is accessible at `s3_path` using aws CLI tools. Thanks again for your help!

````>>> f = h5py.File(s3_path, 'r+', driver='h5s3', aws_access_key=ACCESS_KEY, aws_secret_key=SECRET_KEY, aws_region='us-west-2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/src/pydev/lib/python3.5/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ubuntu/src/pydev/lib/python3.5/site-packages/h5py/_hl/files.py", line 144, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (Request was not a 200. Status was 400:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-west-2' is wrong; expecting 'us-east-1'</Message><Region>us-east-1</Region><RequestId>redacted</RequestId><HostId>redacted</HostId></Error>)````

**Comment by llllllllll** [comment]
hmm, I wonder if we are messing up the region. We have both tested against locally run minio servers and us-east-1, but I don't know about us-west-*. Are you passing a region to `h5py.File`? If not, us-east-1 is the default.
